# Generated by Django 3.0.2 on 2020-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('UserID', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
