# Generated by Django 3.0.2 on 2020-04-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='PlaceofBirth',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Example@gmail.com', max_length=254),
        ),
    ]
